name       : python-wheel
version    : 0.37.0
release    : 14
source     :
    - https://github.com/pypa/wheel/archive/refs/tags/0.37.0.tar.gz : 30cabe12c95f925abcf88490399b693a8a18b2cef0e4938ece5a81c03e4ee7f9
license    : MIT
component  : programming.python
summary    : A built-package format for Python
description: |
    A wheel is a ZIP-format archive with a specially formatted filename and the .whl extension. It is designed to contain all the files for a PEP 376 compatible install in a way that is very close to the on-disk format. Many packages will be properly installed with only the “Unpack” step (simply extracting the file onto sys.path), and the unpacked archive preserves enough information to “Spread” (copy data and scripts to their final locations) at any later time.
builddeps  :
    - pkgconfig(python3)
    - python-jsonschema
    - python-keyring
    - python2-pytest
    - python-pytest
    - python-setuptools
    - pyxdg
setup      : |
    # Don't require pytest-cov for tests
    sed -i 's/--cov=wheel//' setup.cfg
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test
    %python3_test py.test3
