name       : python-wheel
version    : 0.33.6
release    : 5
source     :
    - https://github.com/pypa/wheel/archive/0.33.6.tar.gz : ce9b3af862796aeb7af75c72e54fe974e4bb9a95502f49b1da25fdbf4c53e742
license    : MIT
component  : programming.python
summary    : A built-package format for Python
description: |
    A wheel is a ZIP-format archive with a specially formatted filename and the .whl extension. It is designed to contain all the files for a PEP 376 compatible install in a way that is very close to the on-disk format. Many packages will be properly installed with only the “Unpack” step (simply extracting the file onto sys.path), and the unpacked archive preserves enough information to “Spread” (copy data and scripts to their final locations) at any later time.
builddeps  :
    - pkgconfig(python3)
    - python-jsonschema
    - python-keyring
    - python-pytest-cov
    - python-setuptools
    - pyxdg
build      : |
    %python_setup
    %python3_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
      mv -v "$_f" "${_f%}3"
    done
    %python_install
check      : |
    %python_test py.test
    %python3_test py.test3
